@extends('layouts.admin')
@section('title','Rejection Reasons')
@push('sweetalert')<script src="{{ asset('assets/js/sweetalert2.min.js') }}"></script>@endpush
@section('admin-content')
<div class="space-y-5 p-5 lg:p-6"><div class="flex flex-wrap items-end justify-between gap-3"><div><p class="text-[10px] font-extrabold uppercase tracking-[.2em] text-indigo-600">Property moderation</p><h1 class="mt-1 text-2xl font-extrabold">Rejection Reasons</h1><p class="text-sm text-slate-500">Reasons shown to admins while rejecting a room listing.</p></div><button type="button" id="addReason" class="rounded-xl bg-indigo-600 px-5 py-3 text-sm font-bold text-white"><i class="fas fa-plus mr-2"></i>Add reason</button></div>
@if(session('success'))<div class="rounded-xl border border-emerald-200 bg-emerald-50 p-3 text-sm font-semibold text-emerald-700">{{ session('success') }}</div>@endif
<div class="grid gap-3 sm:grid-cols-3"><div class="rounded-2xl border bg-white p-4"><p class="text-[10px] font-bold uppercase text-slate-400">Active reasons</p><p class="mt-1 text-2xl font-extrabold text-indigo-600">{{ $reasons->count() }}</p></div><div class="rounded-2xl border bg-white p-4 sm:col-span-2"><p class="text-sm font-bold">How it works</p><p class="mt-1 text-xs text-slate-500">Admin selects one reason on the Room Listings page. The selected reason is saved against the room and can be included in the owner notification.</p></div></div>
<div class="overflow-hidden rounded-2xl border bg-white shadow-sm"><div class="border-b px-5 py-4"><h2 class="text-sm font-extrabold">Available moderation reasons</h2></div><div class="divide-y">@forelse($reasons as $index=>$reason)<div class="flex items-center gap-4 px-5 py-4 hover:bg-slate-50"><div class="flex h-9 w-9 shrink-0 items-center justify-center rounded-xl bg-indigo-50 text-xs font-extrabold text-indigo-600">{{ $index+1 }}</div><p class="min-w-0 flex-1 text-sm font-semibold text-slate-700">{{ $reason->reason }}</p><span class="rounded-full bg-emerald-50 px-2.5 py-1 text-[10px] font-bold text-emerald-700">Active</span><button type="button" class="edit-reason rounded-lg border px-3 py-2 text-xs font-bold" data-id="{{ $reason->id }}" data-reason="{{ $reason->reason }}">Edit</button><form method="POST" action="{{ route('admin.rejection-reasons.destroy',$reason) }}" class="delete-reason">@csrf @method('DELETE')<button class="rounded-lg bg-red-50 px-3 py-2 text-xs font-bold text-red-700">Disable</button></form></div>@empty<p class="p-12 text-center text-sm text-slate-500">No active rejection reasons.</p>@endforelse</div></div>
<form id="reasonCreateForm" method="POST" action="{{ route('admin.rejection-reasons.store') }}" class="hidden">@csrf<input name="reason"></form><form id="reasonEditForm" method="POST" class="hidden">@csrf @method('PUT')<input name="reason"></form></div>
@endsection
@push('scripts')<script>
const askReason=async(title,value='')=>Swal.fire({title,input:'text',inputValue:value,inputPlaceholder:'Enter a clear rejection reason',showCancelButton:true,confirmButtonText:'Save reason',confirmButtonColor:'#4f46e5',inputAttributes:{maxlength:255},inputValidator:v=>!v?.trim()?'Reason is required.':undefined});
document.getElementById('addReason').addEventListener('click',async()=>{const r=await askReason('Add rejection reason');if(r.isConfirmed){const f=document.getElementById('reasonCreateForm');f.reason.value=r.value.trim();f.submit();}});
document.querySelectorAll('.edit-reason').forEach(b=>b.addEventListener('click',async()=>{const r=await askReason('Edit rejection reason',b.dataset.reason);if(r.isConfirmed){const f=document.getElementById('reasonEditForm');f.action=`{{ route('admin.rejection-reasons.update',':id') }}`.replace(':id',b.dataset.id);f.reason.value=r.value.trim();f.submit();}}));
document.querySelectorAll('.delete-reason').forEach(f=>f.addEventListener('submit',async e=>{e.preventDefault();const r=await Swal.fire({title:'Disable this reason?',text:'It will no longer appear while rejecting new listings.',icon:'warning',showCancelButton:true,confirmButtonText:'Yes, disable',confirmButtonColor:'#dc2626'});if(r.isConfirmed)f.submit();}));
</script>@endpush
