@extends('layouts.admin')
@section('title','Admin Dashboard')
@push('styles')<style>
.dash-kpis{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:12px}.dash-main{display:grid;grid-template-columns:minmax(0,1.65fr) minmax(310px,.75fr);gap:16px}.dash-recents{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:16px}.dash-queues{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:8px}@media(max-width:1279px){.dash-kpis{grid-template-columns:repeat(2,1fr)}.dash-main{grid-template-columns:1fr}.dash-recents{grid-template-columns:1fr 1fr}}@media(max-width:767px){.dash-kpis,.dash-recents,.dash-queues{grid-template-columns:1fr}}
</style>@endpush
@section('admin-content')
@php $revenueParts=[['Listing fees',$listingEarnings,'#2563eb'],['Featured fees',$featuredEarnings,'#f59e0b'],['Contact unlocks',$unlockEarnings,'#8b5cf6'],['Subscriptions',$subscriptionEarnings,'#10b981']]; @endphp
<div class="space-y-5 p-5 lg:p-6">
<header class="flex flex-wrap items-end justify-between gap-3"><div><p class="text-[10px] font-extrabold uppercase tracking-[.2em] text-indigo-600">Business overview</p><h1 class="mt-1 text-2xl font-extrabold text-slate-900">Good {{ now()->hour<12?'morning':(now()->hour<17?'afternoon':'evening') }}, {{ Auth::user()->name }}</h1><p class="text-sm text-slate-500">Here is what needs attention across ApnaNest today.</p></div><div class="flex gap-2"><a href="{{ route('admin.reports') }}" class="rounded-xl border bg-white px-4 py-2.5 text-xs font-bold"><i class="fas fa-chart-line mr-2 text-indigo-600"></i>View reports</a><a href="{{ route('admin.all-rooms',['listing_status'=>'pending']) }}" class="rounded-xl bg-indigo-600 px-4 py-2.5 text-xs font-bold text-white"><i class="fas fa-list-check mr-2"></i>Review listings</a></div></header>

<section class="dash-kpis"><article class="rounded-2xl border bg-white p-4 shadow-sm"><div class="flex items-start justify-between"><div><p class="text-[10px] font-bold uppercase tracking-wider text-slate-400">Platform revenue</p><p class="mt-2 text-2xl font-extrabold">₹{{ number_format($totalEarnings) }}</p><p class="mt-1 text-[10px] text-slate-500">₹{{ number_format($todayEarnings) }} collected today</p></div><span class="flex h-10 w-10 items-center justify-center rounded-xl bg-indigo-50 text-indigo-600"><i class="fas fa-indian-rupee-sign"></i></span></div></article><article class="rounded-2xl border bg-white p-4 shadow-sm"><div class="flex items-start justify-between"><div><p class="text-[10px] font-bold uppercase tracking-wider text-slate-400">Active listings</p><p class="mt-2 text-2xl font-extrabold">{{ $activeRooms }}</p><p class="mt-1 text-[10px] text-slate-500">{{ $approvedRooms }} total approved</p></div><span class="flex h-10 w-10 items-center justify-center rounded-xl bg-emerald-50 text-emerald-600"><i class="fas fa-building-circle-check"></i></span></div></article><article class="rounded-2xl border bg-white p-4 shadow-sm"><div class="flex items-start justify-between"><div><p class="text-[10px] font-bold uppercase tracking-wider text-slate-400">Users & owners</p><p class="mt-2 text-2xl font-extrabold">{{ $users }}</p><p class="mt-1 text-[10px] text-slate-500">{{ $owners }} property owners</p></div><span class="flex h-10 w-10 items-center justify-center rounded-xl bg-blue-50 text-blue-600"><i class="fas fa-users"></i></span></div></article><article class="rounded-2xl border bg-white p-4 shadow-sm"><div class="flex items-start justify-between"><div><p class="text-[10px] font-bold uppercase tracking-wider text-slate-400">Listing review</p><p class="mt-2 text-2xl font-extrabold">{{ $pendingRooms }}</p><p class="mt-1 text-[10px] text-slate-500">{{ $rejectedRooms }} rejected listings</p></div><span class="flex h-10 w-10 items-center justify-center rounded-xl bg-amber-50 text-amber-600"><i class="fas fa-clock"></i></span></div></article></section>

<section class="dash-main"><div class="rounded-2xl border bg-white p-5 shadow-sm"><div class="flex items-center justify-between"><div><h2 class="text-sm font-extrabold">Monthly platform revenue</h2><p class="text-xs text-slate-500">Listing, featured, unlock and subscription collections in {{ now()->year }}</p></div><div class="text-right"><p class="text-[10px] text-slate-400">This month</p><strong class="text-lg">₹{{ number_format($currentMonthEarnings) }}</strong><span class="ml-2 rounded-full px-2 py-1 text-[10px] font-bold {{ $percentageChange>=0?'bg-emerald-50 text-emerald-700':'bg-red-50 text-red-700' }}">{{ $percentageChange>=0?'↑':'↓' }} {{ abs(round($percentageChange)) }}%</span></div></div><div class="mt-4 h-[280px]"><canvas id="revenueChart"></canvas></div></div>
<aside class="space-y-4"><div class="rounded-2xl border bg-white p-5 shadow-sm"><div class="flex items-center justify-between"><div><h2 class="text-sm font-extrabold">Action required</h2><p class="text-xs text-slate-500">Open operational queues</p></div><span class="rounded-full bg-red-50 px-2.5 py-1 text-[10px] font-bold text-red-700">{{ collect($actionQueues)->sum('count') }} pending</span></div><div class="mt-4 space-y-1">@foreach($actionQueues as $queue)<a href="{{ $queue['route'] }}" class="flex items-center gap-3 rounded-xl px-2 py-2.5 hover:bg-slate-50"><span class="flex h-8 w-8 shrink-0 items-center justify-center rounded-lg bg-slate-100 text-indigo-600"><i class="fas {{ $queue['icon'] }} text-xs"></i></span><span class="min-w-0 flex-1 truncate text-xs font-semibold text-slate-600">{{ $queue['label'] }}</span><strong class="text-sm {{ $queue['count']?'text-slate-900':'text-slate-300' }}">{{ $queue['count'] }}</strong><i class="fas fa-chevron-right text-[8px] text-slate-300"></i></a>@endforeach</div></div></aside></section>

<section class="grid gap-4 lg:grid-cols-2"><div class="rounded-2xl border bg-white p-5"><h2 class="text-sm font-extrabold">Revenue mix</h2><p class="text-xs text-slate-500">Direct-contact platform income by source</p><div class="mt-5 space-y-4">@foreach($revenueParts as [$label,$amount,$color])@php $share=$totalEarnings>0?($amount/$totalEarnings)*100:0; @endphp<div><div class="mb-1.5 flex justify-between text-xs"><span class="font-semibold text-slate-600">{{ $label }}</span><strong>₹{{ number_format($amount) }} <small class="ml-1 text-slate-400">{{ round($share) }}%</small></strong></div><div class="h-2 rounded-full bg-slate-100"><div class="h-2 rounded-full" style="width:{{ min(100,$share) }}%;background:{{ $color }}"></div></div></div>@endforeach</div></div><div class="rounded-2xl border bg-white p-5"><div class="flex justify-between"><div><h2 class="text-sm font-extrabold">Listing health</h2><p class="text-xs text-slate-500">Current moderation distribution</p></div><a href="{{ route('admin.all-rooms') }}" class="text-xs font-bold text-indigo-600">Manage all</a></div><div class="mt-5 grid grid-cols-3 gap-3">@foreach([['Approved',$approvedRooms,'text-emerald-600','bg-emerald-50'],['Pending',$pendingRooms,'text-amber-600','bg-amber-50'],['Rejected',$rejectedRooms,'text-red-600','bg-red-50']] as [$label,$value,$tone,$bg])<div class="rounded-xl {{ $bg }} p-4 text-center"><p class="text-2xl font-extrabold {{ $tone }}">{{ $value }}</p><p class="mt-1 text-[10px] font-bold uppercase text-slate-500">{{ $label }}</p></div>@endforeach</div><div class="mt-4 rounded-xl bg-slate-50 p-4"><div class="flex justify-between text-xs"><span class="text-slate-500">Last month revenue</span><strong>₹{{ number_format($lastMonthEarnings) }}</strong></div><div class="mt-3 flex justify-between text-xs"><span class="text-slate-500">Paid listings</span><strong>{{ $rooms }}</strong></div></div></div></section>

<section class="dash-recents">@foreach([['Recent users',$recentUsers,'admin.users','fa-user'],['Recent owners',$recentOwners,'admin.owners','fa-user-tie']] as [$heading,$records,$route,$icon])<div class="rounded-2xl border bg-white p-5"><div class="flex justify-between"><h2 class="text-sm font-extrabold">{{ $heading }}</h2><a href="{{ route($route) }}" class="text-xs font-bold text-indigo-600">View all</a></div><div class="mt-3 divide-y">@foreach($records as $record)<a href="{{ $route==='admin.owners'?route('admin.owners.detail',$record):route('admin.users.detail',$record) }}" class="flex items-center gap-3 py-3"><span class="flex h-8 w-8 items-center justify-center rounded-lg bg-indigo-50 text-indigo-600"><i class="fas {{ $icon }} text-xs"></i></span><span class="min-w-0 flex-1"><strong class="block truncate text-xs">{{ $record->name }}</strong><small class="text-[10px] text-slate-400">{{ $route==='admin.owners'?$record->rooms_count.' listings':$record->created_at->format('d M Y') }}</small></span><i class="fas fa-chevron-right text-[8px] text-slate-300"></i></a>@endforeach</div></div>@endforeach<div class="rounded-2xl border bg-white p-5"><div class="flex justify-between"><h2 class="text-sm font-extrabold">Recent listings</h2><a href="{{ route('admin.all-rooms') }}" class="text-xs font-bold text-indigo-600">View all</a></div><div class="mt-3 divide-y">@foreach($recentRooms as $room)<a href="{{ route('admin.rooms.show',$room) }}" class="flex items-center gap-3 py-3"><span class="h-8 w-1 rounded-full {{ $room->listing_status==='approved'?'bg-emerald-500':($room->listing_status==='pending'?'bg-amber-500':'bg-red-500') }}"></span><span class="min-w-0 flex-1"><strong class="block truncate text-xs">{{ $room->title??'Room #'.$room->id }}</strong><small class="text-[10px] text-slate-400">{{ $room->owner?->name??'Owner unavailable' }}</small></span><span class="text-[9px] font-bold capitalize text-slate-500">{{ $room->listing_status }}</span></a>@endforeach</div></div></section>

<section class="overflow-hidden rounded-2xl border bg-white"><div class="flex justify-between border-b px-5 py-4"><div><h2 class="text-sm font-extrabold">Recent payments</h2><p class="text-xs text-slate-500">Latest financial activity</p></div><a href="{{ route('admin.payments.index') }}" class="text-xs font-bold text-indigo-600">View all</a></div><div class="overflow-x-auto"><table class="w-full min-w-[760px]"><thead><tr><th>User</th><th>Revenue type</th><th>Amount</th><th>Date</th><th>Status</th></tr></thead><tbody class="divide-y">@forelse($recentPayments as $payment)<tr><td class="px-5 text-xs font-bold">{{ $payment->user?->name??'Deleted user' }}</td><td class="px-5 text-xs capitalize">{{ $payment->type }}</td><td class="px-5 text-xs font-extrabold">₹{{ number_format($payment->amount) }}</td><td class="px-5 text-xs text-slate-500">{{ $payment->created_at->format('d M Y') }}</td><td class="px-5"><span class="rounded-full px-2.5 py-1 text-[10px] font-bold {{ $payment->status==='completed'?'bg-emerald-50 text-emerald-700':'bg-amber-50 text-amber-700' }}">{{ ucfirst($payment->status) }}</span></td></tr>@empty<tr><td colspan="5" class="p-10 text-center text-sm text-slate-500">No payments found.</td></tr>@endforelse</tbody></table></div></section>
</div>
@endsection
@push('scripts')<script src="https://cdn.jsdelivr.net/npm/chart.js"></script><script>const ctx=document.getElementById('revenueChart');if(ctx&&window.Chart)new Chart(ctx,{type:'line',data:{labels:['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'],datasets:[{data:@json($revenueData),borderColor:'#4f46e5',backgroundColor:'rgba(79,70,229,.09)',fill:true,tension:.38,borderWidth:2,pointRadius:3,pointBackgroundColor:'#fff',pointBorderColor:'#4f46e5'}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{display:false},tooltip:{callbacks:{label:c=>'₹'+c.parsed.y.toLocaleString('en-IN')}}},scales:{x:{grid:{display:false}},y:{beginAtZero:true,ticks:{callback:v=>'₹'+Number(v).toLocaleString('en-IN')}}}}});</script>@endpush
