@extends('layouts.admin')
@section('title','Business Reports')
@push('styles')<style>.report-kpis{display:grid;grid-template-columns:repeat(4,1fr);gap:12px}.report-main{display:grid;grid-template-columns:minmax(0,1.3fr) minmax(300px,.7fr);gap:16px}.report-cities{display:grid;grid-template-columns:repeat(5,1fr);gap:10px}@media(max-width:1199px){.report-kpis{grid-template-columns:repeat(2,1fr)}.report-main{grid-template-columns:1fr}.report-cities{grid-template-columns:repeat(3,1fr)}}@media(max-width:639px){.report-kpis,.report-cities{grid-template-columns:1fr}}</style>@endpush
@section('admin-content')
@php $types=['listing'=>'Listing revenue','featured'=>'Featured revenue','subscription'=>'Subscription revenue','unlock'=>'Contact unlock revenue'];$totalRevenue=collect($types)->keys()->sum(fn($t)=>(float)($revenueByType[$t]??0));$max=max(1,(float)$dailyCollections->max('total')); @endphp
<div class="space-y-5 p-5 lg:p-6"><header class="flex flex-wrap items-end justify-between gap-3"><div><p class="text-[10px] font-extrabold uppercase tracking-[.2em] text-indigo-600">Financial intelligence</p><h1 class="mt-1 text-2xl font-extrabold">Reports & Performance</h1><p class="text-sm text-slate-500">Direct-contact revenue, conversion, demand and growth.</p></div><form class="flex flex-wrap gap-2 rounded-xl border bg-white p-2"><input type="date" name="from" value="{{ $from->format('Y-m-d') }}" class="h-10 rounded-lg text-xs"><input type="date" name="to" value="{{ $to->format('Y-m-d') }}" class="h-10 rounded-lg text-xs"><button class="rounded-lg bg-indigo-600 px-4 text-xs font-bold text-white">Apply period</button></form></header>
<section class="report-kpis">@foreach($types as $type=>$label)<article class="rounded-2xl border bg-white p-4"><div class="flex items-center justify-between"><div><p class="text-[10px] font-bold uppercase text-slate-400">{{ $label }}</p><p class="mt-2 text-2xl font-extrabold">₹{{ number_format((float)($revenueByType[$type]??0),2) }}</p><p class="mt-1 text-[10px] text-slate-400">{{ $totalRevenue?round((($revenueByType[$type]??0)/$totalRevenue)*100):0 }}% of revenue</p></div><span class="flex h-10 w-10 items-center justify-center rounded-xl bg-indigo-50 text-indigo-600"><i class="fas {{ $type==='unlock'?'fa-lock-open':($type==='subscription'?'fa-id-card':'fa-indian-rupee-sign') }}"></i></span></div></article>@endforeach</section>
<section class="report-main"><div class="rounded-2xl border bg-white p-5"><div class="flex justify-between"><div><h2 class="text-sm font-extrabold">Daily collections</h2><p class="text-xs text-slate-500">Completed platform revenue in selected period</p></div><strong class="text-xl">₹{{ number_format($totalRevenue,2) }}</strong></div><div class="mt-5 space-y-3">@forelse($dailyCollections as $day)<div class="grid grid-cols-[75px_1fr_100px] items-center gap-3"><span class="text-xs text-slate-500">{{ \Carbon\Carbon::parse($day->day)->format('d M') }}</span><div class="h-2 rounded-full bg-slate-100"><div class="h-2 rounded-full bg-indigo-600" style="width:{{ ($day->total/$max)*100 }}%"></div></div><strong class="text-right text-xs">₹{{ number_format($day->total,2) }}</strong></div>@empty<p class="py-12 text-center text-sm text-slate-500">No completed collections.</p>@endforelse</div></div><aside class="rounded-2xl border bg-white p-5"><h2 class="text-sm font-extrabold">Operational performance</h2><p class="text-xs text-slate-500">Business health during this period</p><div class="mt-4 divide-y">@foreach([['Failed payments',$failedPayments,'text-red-600'],['New owners',$ownerGrowth,'text-blue-600'],['New listings',$listingGrowth,'text-indigo-600'],['Contact unlocks',$unlocks,'text-purple-600'],['Unlock conversion',$totalUsers?round(($unlocks/$totalUsers)*100,1).'%':'0%','text-emerald-600'],['Avg complaint resolution',$resolutionHours?round($resolutionHours,1).' hrs':'No data','text-amber-600']] as [$label,$value,$tone])<div class="flex justify-between py-3 text-xs"><span class="text-slate-500">{{ $label }}</span><strong class="{{ $tone }}">{{ $value }}</strong></div>@endforeach</div></aside></section>
<section class="rounded-2xl border bg-white"><div class="border-b px-5 py-4"><h2 class="text-sm font-extrabold">City-wise demand</h2><p class="text-xs text-slate-500">Enquiries show where users are actively searching.</p></div><div class="report-cities p-5">@forelse($cityDemand as $index=>$city)<div class="rounded-xl bg-slate-50 p-4"><div class="flex justify-between"><span class="text-[10px] font-bold text-slate-400">#{{ $index+1 }}</span><i class="fas fa-location-dot text-indigo-500"></i></div><p class="mt-2 truncate text-sm font-bold">{{ $city->city?:'Unknown' }}</p><p class="mt-1 text-2xl font-extrabold text-indigo-600">{{ $city->total }}</p><p class="text-[10px] text-slate-400">enquiries</p></div>@empty<p class="text-sm text-slate-500">No demand data.</p>@endforelse</div></section></div>
@endsection
