@extends('layouts.admin')
@section('title','Users')
@push('sweetalert')<script src="{{ asset('assets/js/sweetalert2.min.js') }}"></script>@endpush
@push('styles')<style>
.user-filter{display:grid!important;grid-template-columns:minmax(280px,1fr) 190px auto!important;gap:12px;align-items:center}.user-table{table-layout:fixed;width:100%;min-width:900px}.user-table th,.user-table td{text-align:left!important;vertical-align:middle!important;box-sizing:border-box}.user-table th:nth-child(1),.user-table td:nth-child(1){width:30%}.user-table th:nth-child(2),.user-table td:nth-child(2){width:14%}.user-table th:nth-child(3),.user-table td:nth-child(3){width:14%}.user-table th:nth-child(4),.user-table td:nth-child(4){width:24%}.user-table th:nth-child(5),.user-table td:nth-child(5){width:18%;text-align:right!important}.user-table th{padding-left:1.25rem!important;padding-right:1.25rem!important}.user-table td{padding-top:.9rem!important;padding-bottom:.9rem!important}@media(max-width:767px){.user-filter{grid-template-columns:1fr!important}}
</style>@endpush
@section('admin-content')
<div class="space-y-5 p-5 lg:p-6"><div><p class="text-[10px] font-extrabold uppercase tracking-[.2em] text-indigo-600">People management</p><h1 class="mt-1 text-2xl font-extrabold">Platform Users</h1><p class="text-sm text-slate-500">Review account access, payments and contact unlock activity.</p></div>@if(session('success'))<div class="rounded-xl border border-emerald-200 bg-emerald-50 p-3 text-sm font-semibold text-emerald-700">{{ session('success') }}</div>@endif
<form class="user-filter rounded-2xl border bg-white p-4 shadow-sm"><div class="relative"><i class="fas fa-search absolute left-3 top-3.5 text-xs text-slate-400"></i><input name="search" value="{{ request('search') }}" placeholder="Search name or email" class="h-11 w-full rounded-xl border-slate-200 pl-9 text-sm"></div><select name="status" class="h-11 rounded-xl border-slate-200 text-sm"><option value="">All accounts</option><option value="active" @selected(request('status')==='active')>Active</option><option value="blocked" @selected(request('status')==='blocked')>Blocked</option><option value="deleted" @selected(request('status')==='deleted')>Deleted</option></select><div class="flex gap-2"><button class="rounded-xl bg-slate-900 px-5 text-sm font-bold text-white">Apply</button><a href="{{ route('admin.users') }}" class="inline-flex h-11 items-center rounded-xl border px-4 text-sm font-bold text-slate-600">Reset</a></div></form>
<div class="overflow-hidden rounded-2xl border bg-white shadow-sm"><div class="flex items-center justify-between border-b px-5 py-4"><div><h2 class="text-sm font-extrabold">User directory</h2><p class="text-xs text-slate-500">{{ $users->total() }} user accounts</p></div><span class="rounded-full bg-indigo-50 px-3 py-1 text-xs font-bold text-indigo-700">Page {{ $users->currentPage() }} of {{ $users->lastPage() }}</span></div><div class="overflow-x-auto"><table class="user-table"><thead><tr><th>User</th><th>Account</th><th>Joined</th><th>Block reason</th><th>Actions</th></tr></thead><tbody class="divide-y">@forelse($users as $user)<tr class="hover:bg-slate-50/70"><td class="px-5"><div class="flex items-center gap-3"><div class="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-indigo-50 font-extrabold text-indigo-600">{{ strtoupper(substr($user->name,0,1)) }}</div><div class="min-w-0">@if(!$user->trashed())<a href="{{ route('admin.users.detail',$user) }}" class="block truncate text-sm font-bold hover:text-indigo-600">{{ $user->name }}</a>@else<p class="truncate text-sm font-bold">{{ $user->name }}</p>@endif<p class="truncate text-xs text-slate-400">{{ $user->email }} · {{ $user->phone ?: 'No phone' }}</p></div></div></td><td class="px-5"><span class="inline-flex items-center gap-1.5 text-xs font-bold {{ $user->trashed()||$user->is_blocked?'text-red-600':'text-emerald-600' }}"><i class="fas fa-circle text-[6px]"></i>{{ $user->trashed()?'Deleted':($user->is_blocked?'Blocked':'Active') }}</span></td><td class="px-5 text-xs text-slate-500">{{ $user->created_at->format('d M Y') }}</td><td class="px-5"><p class="truncate text-xs text-slate-500" title="{{ $user->block_reason }}">{{ $user->block_reason ?: '—' }}</p></td><td class="px-5"><div class="flex justify-end gap-2">@if($user->trashed())<form method="POST" action="{{ route('admin.members.restore',$user->id) }}">@csrf<button class="rounded-lg bg-emerald-50 px-3 py-2 text-xs font-bold text-emerald-700">Restore</button></form>@else<a href="{{ route('admin.users.detail',$user) }}" class="rounded-lg border px-3 py-2 text-xs font-bold">View</a><form method="POST" action="{{ route('admin.users.toggleBlock',$user) }}" class="user-block-form" data-blocked="{{ $user->is_blocked?'1':'0' }}" data-user="{{ $user->name }}">@csrf<input type="hidden" name="block_reason"><button class="rounded-lg px-3 py-2 text-xs font-bold {{ $user->is_blocked?'bg-emerald-50 text-emerald-700':'bg-red-50 text-red-700' }}">{{ $user->is_blocked?'Unblock':'Block' }}</button></form>@endif</div></td></tr>@empty<tr><td colspan="5" class="p-14 text-center text-sm text-slate-500">No users match these filters.</td></tr>@endforelse</tbody></table></div>@if($users->hasPages())<div class="border-t p-4">{{ $users->withQueryString()->links() }}</div>@endif</div></div>
@endsection
@push('scripts')<script>document.querySelectorAll('.user-block-form').forEach(form=>form.addEventListener('submit',async e=>{e.preventDefault();const blocked=form.dataset.blocked==='1';if(blocked){const result=await Swal.fire({title:'Unblock user?',text:`${form.dataset.user} will regain account access.`,icon:'question',showCancelButton:true,confirmButtonText:'Yes, unblock',confirmButtonColor:'#059669'});if(result.isConfirmed)form.submit();return;}const result=await Swal.fire({title:'Block user account',html:`<p style="font-size:13px;color:#64748b;margin-bottom:12px">Enter an internal reason for blocking <b>${form.dataset.user}</b>.</p>`,input:'textarea',inputPlaceholder:'Enter block reason',inputAttributes:{maxlength:'255'},showCancelButton:true,confirmButtonText:'Block user',confirmButtonColor:'#dc2626',inputValidator:value=>!value?.trim()?'Block reason is required.':undefined});if(result.isConfirmed){form.querySelector('[name=block_reason]').value=result.value.trim();form.submit();}}));</script>@endpush
