<script>
document.addEventListener('DOMContentLoaded',()=>{
 const mode=@json($mode), status=document.getElementById('status-message'), email=document.getElementById('email'), otp=document.getElementById('otp');
 const show=(message,type='error')=>{status.className='auth-alert '+type;status.querySelector('i').className='fas '+(type==='success'?'fa-check-circle':'fa-exclamation-circle');status.querySelector('span').textContent=message;};
 const loading=(button,on)=>{if(on){button.dataset.label=button.innerHTML;button.disabled=true;button.innerHTML='<i class="fas fa-spinner fa-spin"></i><span>Please wait...</span>'}else{button.disabled=false;if(button.dataset.label)button.innerHTML=button.dataset.label}};
 const post=async(url,payload)=>{const response=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json','Accept':'application/json','X-CSRF-TOKEN':document.querySelector('meta[name="csrf-token"]').content},body:JSON.stringify(payload)});let data={};try{data=await response.json()}catch(e){}if(!response.ok&&!data.message)data.message='The request could not be completed.';return data};
 const send=async(button)=>{const address=email.value.trim();if(!/^\S+@\S+\.\S+$/.test(address)){show('Enter a valid email address.');email.focus();return false}loading(button,true);try{const data=await post(@json(route('send.otp')),{email:address});if(!data.success){show(data.message||'We could not send the code. Please try again.');return false}document.getElementById('email-display').textContent=address;document.getElementById(mode==='login'?'email-step':'details-step').classList.add('hidden');document.getElementById('otp-step').classList.remove('hidden');otp.value='';otp.focus();show('Verification code sent. Please check your inbox.','success');return true}catch(e){show('Connection error. Please try again.');return false}finally{loading(button,false)}};
 document.getElementById(mode==='login'?'email-form':'details-form').addEventListener('submit',async e=>{e.preventDefault();if(mode==='register'){const name=document.getElementById('name');if(name.value.trim().length<2){show('Enter your full name.');name.focus();return}if(!document.getElementById('terms_checkbox').checked){show('Please accept the Terms and Privacy Policy.');return}}await send(document.getElementById('send-otp-btn'))});
 document.getElementById('otp-form').addEventListener('submit',async e=>{e.preventDefault();const code=otp.value.replace(/\D/g,'');if(code.length!==6){show('Enter the complete 6-digit verification code.');otp.focus();return}const button=document.getElementById('verify-otp-btn');loading(button,true);const payload={email:email.value.trim(),otp:code};if(mode==='register')Object.assign(payload,{name:document.getElementById('name').value.trim(),phone:document.getElementById('phone').value.trim(),role:document.querySelector('[name="role"]:checked').value,referral_code:document.getElementById('referral_code_input').value.trim()});try{const data=await post(mode==='login'?@json(route('verify.login.otp')):@json(route('verify.registration.otp')),payload);if(data.success){show(mode==='login'?'Login successful. Redirecting...':'Account created. Redirecting...','success');location.href=data.redirect||@json(route('dashboard'));return}show(data.message||'The verification code is invalid or expired.')}catch(e){show('Verification failed. Please try again.')}finally{loading(button,false)}});
 document.getElementById('resend-otp-btn').addEventListener('click',e=>send(e.currentTarget));
 document.getElementById(mode==='login'?'back-to-email-btn':'back-to-details-btn').addEventListener('click',()=>{document.getElementById('otp-step').classList.add('hidden');document.getElementById(mode==='login'?'email-step':'details-step').classList.remove('hidden');status.classList.add('hidden');email.focus()});
 otp.addEventListener('input',()=>otp.value=otp.value.replace(/\D/g,'').slice(0,6));
});
</script>
