@extends('layouts.admin')
@section('title',isset($blog)?'Edit Blog':'Create Blog')
@push('styles')<style>.blog-editor-grid{display:grid!important;grid-template-columns:minmax(0,1fr) 340px!important;gap:20px;align-items:start}.blog-publish{position:sticky;top:86px}.ck-editor__editable{min-height:420px}@media(max-width:1199px){.blog-editor-grid{grid-template-columns:1fr!important}.blog-publish{position:static}}</style>@endpush
@section('admin-content')
<div class="space-y-5 p-5 lg:p-6"><header><a href="{{ route('admin.blogs.index') }}" class="text-xs font-bold text-indigo-600"><i class="fas fa-arrow-left mr-1"></i>All blog posts</a><p class="mt-3 text-[10px] font-extrabold uppercase tracking-[.2em] text-indigo-600">Content management</p><h1 class="mt-1 text-2xl font-extrabold">{{ isset($blog)?'Edit blog post':'Create blog post' }}</h1><p class="text-sm text-slate-500">Write helpful room-rental content and prepare it for search engines.</p></header>
@if(isset($errors)&&$errors->any())<div class="rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-700"><strong>Please correct the form.</strong><ul class="mt-2 list-disc pl-5 text-xs">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
<form action="{{ isset($blog)?route('admin.blogs.update',$blog):route('admin.blogs.store') }}" method="POST" enctype="multipart/form-data" class="blog-editor-grid">@csrf @isset($blog)@method('PUT')@endisset<main class="min-w-0 space-y-5"><section class="rounded-2xl border bg-white p-5"><div><label class="text-xs font-bold">Post title *</label><input id="blogTitle" name="title" maxlength="255" required value="{{ old('title',$blog->title??'') }}" class="mt-2 h-12 w-full rounded-xl border-slate-200 text-base font-bold" placeholder="Example: 10 things to check before renting a room"></div><div class="mt-5"><label class="text-xs font-bold">Article content *</label><textarea name="content" id="editor" rows="18" required class="mt-2 w-full rounded-xl border-slate-200">{{ old('content',$blog->content??'') }}</textarea></div></section><section class="rounded-2xl border bg-white p-5"><div class="flex items-center gap-3"><span class="flex h-10 w-10 items-center justify-center rounded-xl bg-indigo-50 text-indigo-600"><i class="fas fa-magnifying-glass"></i></span><div><h2 class="text-sm font-extrabold">SEO configuration</h2><p class="text-xs text-slate-500">How the article may appear in search results</p></div></div><div class="mt-5 space-y-4"><div><label class="text-xs font-bold">Meta title</label><input name="meta_title" maxlength="255" value="{{ old('meta_title',$blog->meta_title??'') }}" class="mt-2 h-11 w-full rounded-xl border-slate-200 text-sm" placeholder="Leave blank to use the post title"></div><div><label class="text-xs font-bold">Meta description</label><textarea name="meta_description" rows="3" class="mt-2 w-full rounded-xl border-slate-200 text-sm" placeholder="A concise description for Google results">{{ old('meta_description',$blog->meta_description??'') }}</textarea></div><div><label class="text-xs font-bold">Keywords</label><input name="meta_keywords" value="{{ old('meta_keywords',$blog->meta_keywords??'') }}" class="mt-2 h-11 w-full rounded-xl border-slate-200 text-sm" placeholder="room rental, tenant tips, owner guide"></div></div></section></main>
<aside class="blog-publish space-y-4"><section class="rounded-2xl border bg-white p-5"><h2 class="text-sm font-extrabold">Publishing</h2><div class="mt-4 rounded-xl bg-slate-50 p-4"><label class="flex cursor-pointer items-center justify-between"><span><strong class="block text-xs">Publish article</strong><small class="text-[10px] text-slate-500">Turn off to save as draft</small></span><input type="checkbox" name="is_published" value="1" @checked(old('is_published',$blog->is_published??false)) class="h-5 w-5 rounded text-indigo-600"></label></div><button class="mt-4 w-full rounded-xl bg-indigo-600 py-3 text-sm font-bold text-white"><i class="fas fa-paper-plane mr-2"></i>{{ isset($blog)?'Update post':'Save blog post' }}</button><a href="{{ route('admin.blogs.index') }}" class="mt-2 flex h-11 items-center justify-center rounded-xl border text-sm font-bold">Cancel</a></section><section class="rounded-2xl border bg-white p-5"><h2 class="text-sm font-extrabold">Featured image</h2><p class="text-xs text-slate-500">JPG, PNG or GIF · maximum 2 MB</p><label class="mt-4 block cursor-pointer rounded-xl border-2 border-dashed p-3 text-center"><input id="blogImage" type="file" name="image" accept="image/jpeg,image/png,image/gif" class="hidden"><div id="imagePreview">@if(isset($blog)&&$blog->featured_image)<img src="{{ $blog->featured_image }}" class="h-44 w-full rounded-lg object-cover">@else<div class="flex h-40 flex-col items-center justify-center text-slate-400"><i class="fas fa-cloud-arrow-up text-3xl"></i><p class="mt-2 text-xs font-bold">Choose featured image</p></div>@endif</div></label></section><section class="rounded-2xl border bg-indigo-50 p-4 text-xs text-indigo-700"><strong><i class="fas fa-lightbulb mr-2"></i>Publishing tip</strong><p class="mt-2 leading-5">Use a clear title, original image and practical information relevant to owners or room seekers.</p></section></aside></form></div>
@endsection
@include('admin.pages.partials.rich-editor')
@push('scripts')<script>document.addEventListener('DOMContentLoaded',()=>{createRichEditor(document.querySelector('#editor'));document.getElementById('blogImage').addEventListener('change',e=>{const file=e.target.files[0];if(!file)return;document.getElementById('imagePreview').innerHTML=`<img src="${URL.createObjectURL(file)}" class="h-44 w-full rounded-lg object-cover">`})});</script>@endpush
