@extends('layouts.app')
@section('title', $complaint->ticket_number)
@section('content')
@php $isOwner = Auth::user()->role === 'owner'; @endphp
<div class="{{ $isOwner ? 'owner-workspace' : 'user-workspace' }} min-h-screen">
    @include($isOwner ? 'owner.partials.sidebar' : 'user.partials.sidebar', ['active' => 'complaints'])
    <main class="complaint-page-main">
        <header class="{{ $isOwner ? 'owner-page-header' : 'workspace-header' }}"><a href="{{ route('complaints.index') }}" class="text-xs font-bold text-indigo-600">← My Complaints</a><div class="mt-2 flex flex-wrap items-center gap-3"><h1 class="text-2xl font-bold text-slate-900">{{ $complaint->ticket_number }}</h1><span class="rounded-full bg-indigo-50 px-3 py-1 text-xs font-bold text-indigo-700">{{ \App\Models\Complaint::STATUSES[$complaint->status] }}</span></div></header>
        <div class="complaint-page-content complaint-detail-grid">
            <section class="min-w-0 space-y-5">
                <div class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><p class="text-xs font-bold uppercase text-slate-400">{{ \App\Models\Complaint::CATEGORIES[$complaint->category] }}</p><h2 class="mt-1 text-xl font-bold text-slate-900">{{ $complaint->subject }}</h2><p class="mt-4 whitespace-pre-wrap text-sm leading-6 text-slate-600">{{ $complaint->description }}</p>@if($complaint->evidence_path)<a href="{{ route('complaints.evidence', $complaint) }}" class="mt-4 inline-flex items-center gap-2 text-sm font-bold text-indigo-600"><i class="fas fa-paperclip"></i> Download evidence</a>@endif</div>
                <div class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h3 class="font-bold text-slate-900">Conversation</h3><div class="mt-4 space-y-4">@forelse($complaint->replies as $reply)<div class="rounded-xl {{ $reply->user->role === 'admin' ? 'bg-indigo-50' : 'bg-slate-50' }} p-4"><div class="flex justify-between text-xs"><strong>{{ $reply->user->role === 'admin' ? 'ApnaNest Support' : $reply->user->name }}</strong><span class="text-slate-400">{{ $reply->created_at->format('d M Y, h:i A') }}</span></div><p class="mt-2 whitespace-pre-wrap text-sm text-slate-700">{{ $reply->message }}</p>@if($reply->attachment_path)<a href="{{ route('complaints.attachment', [$complaint, $reply]) }}" class="mt-2 inline-block text-xs font-bold text-indigo-600">Download attachment</a>@endif</div>@empty<p class="text-sm text-slate-500">Support responses will appear here.</p>@endforelse</div></div>
                @unless(in_array($complaint->status, ['closed','rejected']))<form action="{{ route('complaints.reply', $complaint) }}" method="POST" enctype="multipart/form-data" class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm">@csrf<h3 class="font-bold text-slate-900">Add information</h3><textarea name="message" rows="4" required class="mt-3 w-full rounded-xl border-slate-300" placeholder="Write a reply..."></textarea><input type="file" name="attachment" accept=".jpg,.jpeg,.png,.webp,.pdf" class="mt-3 block w-full text-sm"><button class="mt-4 rounded-xl bg-indigo-600 px-5 py-2.5 text-sm font-bold text-white">Send Reply</button></form>@endunless
            </section>
            <aside class="min-w-0 h-fit space-y-5"><div class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h3 class="font-bold text-slate-900">Ticket details</h3><dl class="mt-4 space-y-4 text-sm"><div><dt class="text-xs text-slate-400">Created</dt><dd class="font-semibold">{{ $complaint->created_at->format('d M Y, h:i A') }}</dd></div><div><dt class="text-xs text-slate-400">Property</dt><dd class="font-semibold">{{ $complaint->room?->title ?? 'General complaint' }}</dd></div><div><dt class="text-xs text-slate-400">Priority</dt><dd class="font-semibold capitalize">{{ $complaint->priority }}</dd></div>@if($complaint->resolution)<div><dt class="text-xs text-slate-400">Resolution</dt><dd class="mt-1 whitespace-pre-wrap text-slate-700">{{ $complaint->resolution }}</dd></div>@endif</dl></div><div class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h3 class="font-bold text-slate-900">Activity</h3><ol class="mt-4 space-y-4">@foreach($complaint->activities->sortByDesc('created_at') as $activity)<li class="border-l-2 border-indigo-200 pl-3"><p class="text-xs font-semibold text-slate-700">{{ $activity->description }}</p>@if($activity->status_to)<p class="mt-1 text-xs text-indigo-600">{{ \App\Models\Complaint::STATUSES[$activity->status_to] ?? $activity->status_to }}</p>@endif<p class="mt-1 text-[10px] text-slate-400">{{ $activity->created_at->format('d M Y, h:i A') }}</p></li>@endforeach</ol></div></aside>
        </div>
    </main>
</div>
@endsection
