<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{{ $title ?? 'ApnaNest' }}</title></head>
<body style="margin:0;background:#f1f5f9;color:#334155;font-family:Arial,'Segoe UI',sans-serif;">
<div style="display:none;max-height:0;overflow:hidden;opacity:0;">{{ $preheader ?? $title ?? 'An update from ApnaNest' }}</div>
<table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="background:#f1f5f9;"><tr><td align="center" style="padding:32px 12px;">
<table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="max-width:620px;background:#fff;border:1px solid #dbe3ef;border-radius:16px;overflow:hidden;box-shadow:0 8px 24px rgba(15,23,42,.07);">
<tr><td style="padding:25px 30px;background:#0f172a;border-top:5px solid #2563eb;"><a href="{{ config('app.url') }}" style="color:#fff;text-decoration:none;font-size:24px;font-weight:800;letter-spacing:-.5px;">Apna<span style="color:#60a5fa;">Nest</span></a><div style="color:#94a3b8;font-size:12px;margin-top:4px;">Find a room. List a property. Connect directly.</div></td></tr>
<tr><td style="padding:34px 30px;line-height:1.65;font-size:15px;">@yield('content')</td></tr>
<tr><td style="padding:22px 30px;background:#f8fafc;border-top:1px solid #e2e8f0;text-align:center;color:#64748b;font-size:12px;line-height:1.6;">This is an automated service email from ApnaNest.<br>&copy; {{ date('Y') }} ApnaNest. All rights reserved.<br><a href="{{ url('/privacy-policy') }}" style="color:#2563eb;">Privacy Policy</a>&nbsp;&nbsp;&bull;&nbsp;&nbsp;<a href="{{ url('/contact-us') }}" style="color:#2563eb;">Contact Support</a></td></tr>
</table></td></tr></table>
<style>.badge{display:inline-block;padding:6px 11px;border-radius:999px;font-size:11px;font-weight:700;text-transform:uppercase;letter-spacing:.5px}.badge-primary{background:#dbeafe;color:#1d4ed8}.badge-success{background:#dcfce7;color:#15803d}.badge-warning{background:#fef3c7;color:#a16207}.badge-danger{background:#fee2e2;color:#b91c1c}.btn{display:inline-block;padding:13px 22px;background:#2563eb;color:#fff!important;text-decoration:none;border-radius:9px;font-weight:700}.notice{padding:14px 16px;border-radius:9px;margin:22px 0;font-size:14px}.notice-primary{background:#eff6ff;color:#1e40af;border-left:4px solid #2563eb}.notice-success{background:#f0fdf4;color:#166534;border-left:4px solid #22c55e}.notice-warning{background:#fffbeb;color:#92400e;border-left:4px solid #f59e0b}.notice-danger{background:#fef2f2;color:#991b1b;border-left:4px solid #ef4444}.fallback-link{font-size:12px!important;color:#64748b!important;word-break:break-all}.fallback-link a{color:#2563eb}h2{margin:0 0 14px;color:#0f172a;font-size:25px;line-height:1.25}p{margin:0 0 16px}@media(max-width:640px){.email-content{padding:25px 20px!important}}</style>
</body></html>
